import { isOpenAt } from "./hours";
import type { AdminScores, Shop, WeeklyHours } from "./types";

const neutralEditorScore: AdminScores = { soup: 3, noodles: 3, toppings: 3, completeness: 3 };
const daily = (ranges: Array<{ open: string; close: string }>): WeeklyHours => ({ 0: ranges, 1: ranges, 2: ranges, 3: ranges, 4: ranges, 5: ranges, 6: ranges });

const records: Omit<Shop, "openNow">[] = [
  {
    id: "chikumo-guanghua",
    slug: "chikumo-guanghua",
    brand: "麵屋千雲",
    name: "麵屋千雲 光華店",
    area: "忠孝新生",
    address: "台北市中正區臨沂街3巷1號",
    lat: 25.043373,
    lng: 121.53103,
    basePrice: 290,
    googleRating: 4.7,
    openingHours: daily([{ open: "11:00", close: "01:30" }]),
    hoursSummary: "每日 11:00–翌日 01:30",
    recommendationReady: true,
    description: "以雞白湯、柚香鹽味雞湯與魚介沾麵為主，鄰近忠孝新生站。",
    queue: { weekdayLunch: "under30", weekdayDinner: "under30", holidayLunch: "over30", holidayDinner: "over30", offPeak: "none" },
    adminScores: neutralEditorScore,
    editorialStatus: "neutral",
    dataSources: ["GoFind 2026 台北拉麵榜", "Uber Eats 店家頁", "MENU 美食誌"],
    verifiedAt: "2026-07-25",
  },
  {
    id: "chikumo-linsen",
    slug: "chikumo-linsen",
    brand: "麵屋千雲",
    name: "麵屋千雲 林森店",
    area: "林森北路",
    address: "台北市中山區林森北路105-1號",
    lat: 25.050267,
    lng: 121.525,
    basePrice: 290,
    googleRating: 4.5,
    openingHours: daily([{ open: "11:00", close: "04:00" }]),
    hoursSummary: "每日 11:00–翌日 04:00",
    recommendationReady: true,
    description: "深夜仍可吃到雞白湯與柚香鹽味雞湯，是中山一帶的宵夜選項。",
    queue: { weekdayLunch: "under30", weekdayDinner: "over30", holidayLunch: "over30", holidayDinner: "over30", offPeak: "under30" },
    adminScores: neutralEditorScore,
    editorialStatus: "neutral",
    dataSources: ["GoFind 2026 中山區拉麵榜", "2026 店家食記", "foodpanda 店家頁"],
    verifiedAt: "2026-07-25",
  },
  {
    id: "tonchin-taipei-main",
    slug: "tonchin-taipei-main",
    brand: "屯京拉麵",
    name: "屯京拉麵 台北站前店",
    area: "台北車站",
    address: "台北市中正區忠孝西路一段38號B1",
    lat: 25.046239,
    lng: 121.5164,
    basePrice: 310,
    googleRating: 4.2,
    openingHours: { 0: [{ open: "10:00", close: "22:30" }], 1: [{ open: "11:00", close: "22:00" }], 2: [{ open: "11:00", close: "22:00" }], 3: [{ open: "11:00", close: "22:00" }], 4: [{ open: "11:00", close: "22:00" }], 5: [{ open: "11:00", close: "22:00" }], 6: [{ open: "10:00", close: "22:30" }] },
    hoursSummary: "平日 11:00–22:00；六日 10:00–22:30",
    recommendationReady: true,
    description: "位於台北凱撒大飯店 B1，主打東京豚骨拉麵，從台北車站步行即可抵達。",
    queue: { weekdayLunch: "under30", weekdayDinner: "under30", holidayLunch: "over30", holidayDinner: "under30", offPeak: "none" },
    adminScores: neutralEditorScore,
    editorialStatus: "neutral",
    dataSources: ["Foodex Group 官方門市頁", "Uber Eats 店家頁"],
    verifiedAt: "2026-07-25",
  },
  {
    id: "ichiran-taipei",
    slug: "ichiran-taipei",
    brand: "一蘭",
    name: "一蘭 台灣台北本店",
    area: "信義",
    address: "台北市信義區松仁路97號",
    lat: 25.03636,
    lng: 121.56925,
    basePrice: 310,
    googleRating: 4.2,
    openingHours: { 0: [{ open: "00:00", close: "24:00" }], 1: [{ open: "10:00", close: "05:00" }], 2: [{ open: "10:00", close: "05:00" }], 3: [{ open: "10:00", close: "05:00" }], 4: [{ open: "10:00", close: "05:00" }], 5: [{ open: "00:00", close: "24:00" }], 6: [{ open: "00:00", close: "24:00" }] },
    hoursSummary: "一至四 10:00–翌日 05:00；五至日與假日 24 小時",
    recommendationReady: true,
    description: "位於松仁路的天然豚骨拉麵店，週末與假日為 24 小時營業。",
    queue: { weekdayLunch: "over30", weekdayDinner: "over30", holidayLunch: "over30", holidayDinner: "over30", offPeak: "under30" },
    adminScores: neutralEditorScore,
    editorialStatus: "neutral",
    dataSources: ["一蘭台灣官方門市頁", "OpenStreetMap / Mapcarta"],
    verifiedAt: "2026-07-25",
  },
  {
    id: "douraku-shop",
    slug: "douraku-shop",
    brand: "道樂",
    name: "道樂商店",
    area: "西門",
    address: "台北市萬華區成都路27巷12號",
    lat: 25.04308,
    lng: 121.50686,
    basePrice: 250,
    googleRating: 4.4,
    openingHours: daily([{ open: "12:00", close: "14:00" }, { open: "17:00", close: "21:00" }]),
    hoursSummary: "每日 12:00–14:00、17:00–21:00",
    recommendationReady: true,
    description: "藏在西門町巷內，以豚骨、雞白湯與沾麵為主的昭和風拉麵店。",
    queue: { weekdayLunch: "under30", weekdayDinner: "under30", holidayLunch: "over30", holidayDinner: "over30", offPeak: "none" },
    adminScores: neutralEditorScore,
    editorialStatus: "neutral",
    dataSources: ["MENU 美食誌 2026", "Corner 2026", "OpenStreetMap 鄰近門牌座標"],
    verifiedAt: "2026-07-25",
  },
];

export const shops: Shop[] = records.map((shop) => ({ ...shop, openNow: isOpenAt(shop.openingHours) }));
