export type Coordinates = { lat: number; lng: number };
export type BudgetChoice = "cheap" | "standard" | "unlimited";
export type QueueChoice = "none" | "under30" | "unlimited";
export type QueueLevel = "none" | "under30" | "over30" | "unknown";
export type NoveltyChoice = "new" | "repeat";
export type QueueEstimate = { weekdayLunch: QueueLevel; weekdayDinner: QueueLevel; holidayLunch: QueueLevel; holidayDinner: QueueLevel; offPeak: QueueLevel };
export type AdminScores = { soup: number; noodles: number; toppings: number; completeness: number };
export type TimeRange = { open: string; close: string };
export type WeeklyHours = Partial<Record<0 | 1 | 2 | 3 | 4 | 5 | 6, TimeRange[]>>;
export type Shop = {
  id: string;
  slug: string;
  brand: string;
  name: string;
  area: string;
  address: string;
  lat: number;
  lng: number;
  basePrice: number;
  googleRating: number;
  openNow: boolean;
  openingHours: WeeklyHours;
  hoursSummary: string;
  recommendationReady: boolean;
  description: string;
  queue: QueueEstimate;
  adminScores: AdminScores;
  editorialStatus: "neutral" | "reviewed";
  dataSources: string[];
  verifiedAt: string;
};
export type RecommendationPreferences = { walkMinutes: number; budget: BudgetChoice; queue: QueueChoice; novelty: NoveltyChoice; eatenIds: Set<string> };
export type RecommendationResult = { selected: Shop | null; alternatives: Shop[]; ranked: Array<{ shop: Shop; score: number }>; reason: string };
